import { categories, productTypes } from "@/lib/constants";

export type Category = (typeof categories)[number];
export type ProductType = (typeof productTypes)[number];

export type Product = {
  id: number;
  slug: string;
  name: string;
  category: Category | readonly Category[];
  type: ProductType;
  price?: number;
  popularity: number;
  isLatest: boolean;
  image: string;
  shortUsage: string;
  description: string;
  dosage: string;
  usage: string;
  benefits: string[];
  packaging: string;
  composition: string;
  warnings?: string;
};

export const products: Product[] = [
  {
    id: 1,
    slug: "welmax-plus",
    name: "WELMAX PLUS",
    image: "/products/Copy of welmax plus.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 96,
    isLatest: true,
    shortUsage: "Oxyclozanide, Levamisole & Silymarin Suspension",
    description:
      "WELMAX PLUS is a deworming formulation enriched with Silymarin to support liver health and recovery.",
    dosage: "1 ml/4 kg body weight",
    usage:
      "Used for parasite management while supporting liver function.",
    benefits: [
      "Hepatoprotective support",
      "Improves recovery",
      "Enhances performance",
      "Supports overall productivity",
    ],
    packaging: "500 ml, 1 L",
    composition: "Oxyclozanide 60 mg + Levamisole 30 mg + Silymarin 4 mg/ml",
  },
  {
    id: 2,
    slug: "trisole",
    name: "TRISOLE",
    image: "/products/Copy of trisole.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 96,
    isLatest: false,
    shortUsage: "Triclabendazole Oral Suspension",
    description:
      "TRISOLE is a triclabendazole-based dewormer formulated for effective liver fluke control and improved livestock productivity.",
    dosage: "1 ml/5 kg body weight",
    usage:
      "Used for the treatment and control of liver fluke infestations.",
    benefits: [
      "Improves liver function",
      "Enhances productivity",
      "Supports feed conversion",
      "Controls liver flukes",
    ],
    packaging: "250 ml, 500 ml, 1 L",
    composition: "Triclabendazole 50 mg/ml",
  },
  {
    id: 3,
    slug: "stanpiperz-45",
    name: "STANPIPERZ 45",
    image: "/products/STANPIPERZ 45.png",
    category: "Poultry",
    type: "Dewormers",
    popularity: 80,
    isLatest: false,
    shortUsage: "Deworming solution",
    description:
      "STANPIPERZ 45 is a veterinary deworming formulation used against internal parasites.",
    dosage: "As directed by veterinarian",
    usage: "Used for treatment and control of internal parasites.",
    benefits: ["Controls parasitic infestations", "Improves animal health"],
    packaging: "As per PPT",
    composition: "Piperazine based formulation",
  },
  {
    id: 4,
    slug: "stanmisole",
    name: "STANMISOLE",
    image: "/products/STANMISOLE.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Dewormers",
    popularity: 92,
    isLatest: false,
    shortUsage: "Levamisole HCl Soluble Powder",
    description:
      "STANMISOLE is a levamisole-based broad-spectrum dewormer formulated for the control of gastrointestinal worms and nematode infestations in poultry.",
    dosage: "Administer as directed by veterinarian or product label.",
    usage:
      "Recommended for the treatment and control of gastrointestinal worms and nematode infestations in poultry.",
    benefits: [
      "Broad-spectrum deworming action",
      "Controls gastrointestinal worms",
      "Supports flock health",
      "Improves productivity",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Levamisole HCl 30% Soluble Powder",
  },
  {
    id: 5,
    slug: "stanmectin",
    name: "STANMECTIN",
    image: "/products/STANMECTIN.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 96,
    isLatest: true,
    shortUsage: "Broad spectrum antiparasitic solution",
    description:
      "STANMECTIN is an ivermectin oral solution effective against internal and external parasites.",
    dosage: "1 ml per 4 kg body weight",
    usage: "Used against roundworms, lungworms, lice, and mange mites.",
    benefits: [
      "Broad-spectrum dewormer",
      "Improves productivity",
      "Controls endo & ecto parasites",
      "Relieves skin irritation",
    ],
    packaging: "100 ml, 500 ml, 1 Ltr",
    composition: "Ivermectin I.P. 0.8 mg",
  },
  {
    id: 6,
    slug: "rafosole",
    name: "RAFOSOLE",
    image: "/products/Copy of rafosole.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 98,
    isLatest: false,
    shortUsage: "Rafoxanide & Levamisole Oral Suspension",
    description:
      "RAFOSOLE is a broad-spectrum dewormer formulated to control internal parasites and support livestock productivity.",
    dosage: "1 ml/2 kg body weight",
    usage:
      "Used for the treatment and control of parasitic infestations.",
    benefits: [
      "Improves weight gain",
      "Enhances milk production",
      "Supports fertility",
      "Reduces parasite burden",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Rafoxanide 15 mg + Levamisole 15 mg/ml",
  },
  {
    id: 7,
    slug: "rafosole-ds",
    name: "RAFOSOLE-DS",
    image: "/products/Copy of rafosole ds.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 97,
    isLatest: false,
    shortUsage: "Rafoxanide & Levamisole Oral Suspension",
    description:
      "RAFOSOLE-DS is a concentrated deworming formulation designed to improve livestock productivity and parasite control.",
    dosage: "1 ml/4 kg body weight",
    usage:
      "Used for the treatment and control of internal parasites.",
    benefits: [
      "Improves weight gain",
      "Enhances milk production",
      "Supports fertility",
      "Broad-spectrum control",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Rafoxanide 30 mg + Levamisole 30 mg/ml",
  },
  {
    id: 8,
    slug: "rafosole-i",
    name: "RAFOSOLE-I",
    image: "/products/Copy of rafosole i.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 98,
    isLatest: true,
    shortUsage: "Rafoxanide & Ivermectin Oral Suspension",
    description:
      "RAFOSOLE-I combines rafoxanide and ivermectin for broad-spectrum parasite control and improved productivity.",
    dosage: "1 ml/4 kg body weight",
    usage:
      "Used for the treatment and control of internal parasites.",
    benefits: [
      "Improves weight gain",
      "Enhances milk production",
      "Supports fertility",
      "Broad-spectrum parasite control",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Rafoxanide 30 mg + Ivermectin 1 mg/ml",
  },
  {
    id: 9,
    slug: "rafosole-i-plus",
    name: "RAFOSOLE-I PLUS",
    image: "/products/Copy of rafosole i plus.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 99,
    isLatest: true,
    shortUsage: "Rafoxanide & Ivermectin Oral Suspension",
    description:
      "RAFOSOLE-I PLUS is a premium broad-spectrum dewormer formulated to improve fertility, productivity, and parasite control.",
    dosage: "1 ml/5 kg body weight",
    usage:
      "Used for the treatment and control of internal parasites.",
    benefits: [
      "Improves fertility",
      "Reduces mortality",
      "Broad-spectrum control",
      "Supports productivity",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Rafoxanide 35 mg + Ivermectin 2 mg/ml",
  },
  {
    id: 10,
    slug: "oxysole-n",
    name: "OXYSOLE-N",
    image: "/products/Copy of oxysole n.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 95,
    isLatest: false,
    shortUsage: "Niclosamide & Oxyclozanide Oral Suspension",
    description:
      "OXYSOLE-N is a dual-action dewormer formulated to support parasite control and improve productivity in sheep and goats.",
    dosage: "1 ml/1.5 kg body weight",
    usage:
      "Used for the treatment and control of parasitic infestations.",
    benefits: [
      "Improves weight gain",
      "Supports appetite",
      "Enhances milk production",
      "Reduces parasite burden",
    ],
    packaging: "250 ml, 500 ml, 1 L",
    composition: "Niclosamide 120 mg + Oxyclozanide 30 mg/ml",
  },
  {
    id: 11,
    slug: "niclomax-plus",
    name: "NICLOMAX PLUS",
    image: "/products/NICLOMAX PLUS.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Dewormers",
    popularity: 89,
    isLatest: true,
    shortUsage: "Broad spectrum cestocidal dewormer",
    description:
      "NICLOMAX PLUS is a broad-spectrum antiparasitic formulation for poultry and livestock.",
    dosage: "1 ml per 1.5 kg body weight",
    usage: "Used against intestinal tapeworms, cestodes, and GI nematodes.",
    benefits: [
      "Improves body weight gain",
      "Improves milk production",
      "Reduces mortality",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 Ltr",
    composition: "Niclosamide I.P. 500 mg + Albendazole I.P. 150 mg",
  },
  {
    id: 12,
    slug: "clozomax",
    name: "CLOZOMAX",
    image: "/products/Copy of clozomax.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 98,
    isLatest: false,
    shortUsage: "Closantel Oral Solution",
    description:
      "CLOZOMAX is a closantel-based dewormer effective against liver flukes and blood-sucking parasites in sheep and goats.",
    dosage:
      "1 ml/15 kg body weight (flukes); 1 ml/10 kg body weight (blood-sucking parasites)",
    usage:
      "Recommended for the treatment and control of liver flukes and blood-feeding parasites.",
    benefits: [
      "Reduces fluke and worm load",
      "Controls blood-sucking parasites",
      "Improves appetite and body weight",
      "Supports milk production",
    ],
    packaging: "30 ml, 100 ml, 250 ml, 500 ml, 1 L",
    composition: "Closantel 150 mg/ml",
  },
  {
    id: 13,
    slug: "auromax-soluble-powder",
    name: "AUROMAX SOLUBLE POWDER",
    image: "/products/auromax.png",
    category: "Sheep & Goat",
    type: "Antibiotics",
    popularity: 91,
    isLatest: false,
    shortUsage: "Chlortetracycline HCl 5.5% Soluble Powder",
    description:
      "AUROMAX SOLUBLE POWDER is a broad-spectrum tetracycline antibiotic formulated to support the treatment and control of bacterial infections in poultry and livestock. Its rapid absorption and wide tissue distribution help promote faster recovery and improved performance.",
    dosage: "1 g per 3–5 kg body weight for 5–7 days",
    usage:
      "Recommended for the treatment and control of bacterial infections caused by susceptible organisms affecting the respiratory, gastrointestinal, and systemic systems.",
    benefits: [
      "Fast-acting antibacterial action",
      "Broad-spectrum coverage against susceptible bacteria",
      "Supports faster recovery and growth",
      "Rapid tissue distribution for effective treatment",
    ],
    packaging: "100 g, 1 kg",
    composition: "Chlortetracycline HCl 5.5% W/w Soluble Powder",
  },
  {
    id: 14,
    slug: "auromax-20",
    name: "AUROMAX 20",
    image: "/products/auromax 20.png",
    category: "Sheep & Goat",
    type: "Antibiotics",
    popularity: 92,
    isLatest: false,
    shortUsage: "Chlortetracycline HCl 20% Soluble Powder",
    description:
      "AUROMAX 20 is a concentrated broad-spectrum antibiotic soluble powder containing Chlortetracycline HCl. It is designed for the effective management of bacterial infections, supporting rapid recovery, better feed utilization, and overall flock health.",
    dosage: "1 g per 10–15 kg body weight for 5–7 days",
    usage:
      "Recommended for the treatment and control of bacterial respiratory, enteric, and systemic infections caused by organisms susceptible to chlortetracycline.",
    benefits: [
      "Fast-acting antibacterial activity",
      "Broad-spectrum protection against bacterial infections",
      "Supports recovery, growth, and productivity",
      "Rapid absorption and tissue distribution",
    ],
    packaging: "1 kg",
    composition: "Chlortetracycline HCl 20% W/w (200 mg/g) Soluble Powder",
  },
  {
    id: 15,
    slug: "bactodox",
    name: "BACTODOX",
    image: "/products/bactodox.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 92,
    isLatest: false,
    shortUsage: "Neomycin & Doxycycline Water Soluble Powder",
    description:
      "BACTODOX is a broad-spectrum antibiotic combination formulated to control respiratory and enteric bacterial infections in poultry. It helps reduce chick mortality and effectively manages diarrhea and secondary bacterial complications.",
    dosage: "1 g/10 L water (prevention); 1 g/5 L water (treatment)",
    usage:
      "Recommended for respiratory infections, enteric bacterial diseases, diarrhea, and prevention of early chick mortality.",
    benefits: [
      "Broad-spectrum antibacterial action",
      "Controls respiratory infections",
      "Controls enteric infections and diarrhea",
      "Reduces early chick mortality",
    ],
    packaging: "50 g, 100 g, 250 g",
    composition: "Neomycin 10% + Doxycycline HCl 10%",
  },
  {
    id: 16,
    slug: "cipromax",
    name: "CIPROMAX",
    image: "/products/cipromax.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Antibiotics",
    popularity: 94,
    isLatest: false,
    shortUsage: "Ciprofloxacin Water Soluble Powder",
    description:
      "CIPROMAX is a broad-spectrum fluoroquinolone antibiotic that provides rapid absorption and excellent tissue penetration for effective control of bacterial infections in poultry.",
    dosage: "1 g/L water or 1 g/10 kg body weight",
    usage:
      "Recommended for the treatment and control of E. coli and other susceptible bacterial infections.",
    benefits: [
      "Broad-spectrum antibacterial activity",
      "Rapid absorption",
      "Excellent tissue penetration",
      "Effective against E. coli infections",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Ciprofloxacin HCl 100 mg/g",
  },
  {
    id: 17,
    slug: "cipromax-ds",
    name: "CIPROMAX-DS",
    image: "/products/cipromax ds.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Antibiotics",
    popularity: 95,
    isLatest: false,
    shortUsage: "High Strength Ciprofloxacin Water Soluble Powder",
    description:
      "CIPROMAX-DS is a high-potency ciprofloxacin formulation designed for rapid control of severe bacterial infections in poultry with enhanced antibacterial efficacy.",
    dosage: "1 g/2 L water or 1 g/20 kg body weight",
    usage:
      "Recommended for severe bacterial infections including E. coli and other susceptible pathogens.",
    benefits: [
      "High-strength antibacterial formulation",
      "Rapid absorption",
      "Excellent tissue penetration",
      "Effective against E. coli infections",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Ciprofloxacin HCl 200 mg/g",
  },
  {
    id: 18,
    slug: "dazimax",
    name: "DAZIMAX",
    image: "/products/dazimax.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 91,
    isLatest: false,
    shortUsage: "Sulfachloropyridazine & Trimethoprim Powder",
    description:
      "DAZIMAX is a synergistic antibacterial formulation effective against a wide range of bacterial infections affecting poultry health and productivity.",
    dosage: "1 g/5 kg body weight for 3–6 days",
    usage:
      "Recommended for bacterial infections, air-sac disease, coliform septicemia, and salpingitis.",
    benefits: [
      "Controls bacterial infections",
      "Effective against air-sac disease",
      "Supports recovery from septicemia",
      "Improves flock health",
    ],
    packaging: "100 g, 250 g",
    composition: "Sulfachloropyridazine Sodium 100 mg/g + Trimethoprim 20 mg/g",
  },
  {
    id: 19,
    slug: "diazeprim-vet",
    name: "DIAZEPRIM (VET)",
    image: "/products/diazedprim powder.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Antibiotics",
    popularity: 93,
    isLatest: false,
    shortUsage: "Sulphadiazine & Trimethoprim Oral Solution",
    description:
      "DIAZEPRIM (VET) is a broad-spectrum antibacterial formulation designed to control major bacterial diseases affecting poultry.",
    dosage: "4 ml/5 L water for 4–6 days",
    usage:
      "Recommended for infections caused by E. coli, Haemophilus, Pasteurella, Salmonella, Staphylococcus, and Streptococcus species.",
    benefits: [
      "Broad-spectrum antibacterial activity",
      "Controls E. coli infections",
      "Effective against Salmonella",
      "Supports flock recovery",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Sulphadiazine 100 mg/g + Trimethoprim 20 mg/g",
  },
  {
    id: 20,
    slug: "endocin-ds",
    name: "ENDOCIN-DS",
    image: "/products/endocin ds.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 96,
    isLatest: false,
    shortUsage: "Enrofloxacin Oral Solution",
    description:
      "ENDOCIN-DS is a broad-spectrum bactericidal antibiotic solution offering rapid action against major poultry bacterial pathogens.",
    dosage: "1 ml/4 L water (prevention); 1 ml/2 L water (treatment)",
    usage:
      "Recommended for E. coli, Mycoplasma, and other susceptible bacterial infections.",
    benefits: [
      "Broad-spectrum bactericidal action",
      "Effective against E. coli",
      "Controls Mycoplasma infections",
      "Rapid therapeutic response",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L, 5 L",
    composition: "Enrofloxacin 100 mg/ml",
  },
  {
    id: 21,
    slug: "endocin-bh",
    name: "ENDOCIN-BH",
    image: "/products/endocin bh.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 97,
    isLatest: false,
    shortUsage: "Enrofloxacin & Bromhexine Oral Solution",
    description:
      "ENDOCIN-BH combines the antibacterial action of enrofloxacin with the mucolytic effect of bromhexine for superior respiratory infection management in poultry.",
    dosage: "1 ml/4 L water (prevention); 1 ml/2 L water (treatment)",
    usage:
      "Recommended for respiratory and bacterial infections caused by E. coli, Mycoplasma, and other susceptible pathogens.",
    benefits: [
      "Broad-spectrum bactericidal action",
      "Supports respiratory health",
      "Effective against E. coli and Mycoplasma",
      "Improves recovery from respiratory infections",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L, 5 L",
    composition: "Enrofloxacin 200 mg/ml + Bromhexine HCl 15 mg/ml",
  },
  {
    id: 22,
    slug: "maxazit",
    name: "MAXAZIT",
    image: "/products/maxazit powder.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 94,
    isLatest: false,
    shortUsage: "Azithromycin Water Soluble Powder",
    description:
      "MAXAZIT is an azithromycin-based antibiotic formulated for effective control of chronic respiratory diseases and bacterial infections in poultry with excellent tissue penetration.",
    dosage: "1 g per 5–10 kg body weight",
    usage:
      "Recommended for chronic respiratory disease (CRD) and other respiratory bacterial infections.",
    benefits: [
      "Excellent tissue penetration",
      "Controls respiratory infections",
      "Supports faster recovery",
      "Improves flock performance",
    ],
    packaging: "100 g, 1 kg",
    composition: "Azithromycin 100 mg/g",
  },
  {
    id: 23,
    slug: "neoforte",
    name: "NEOFORTE",
    image: "/products/neoforte.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 92,
    isLatest: false,
    shortUsage: "Neomycin Sulphate Water Soluble Powder",
    description:
      "NEOFORTE is a neomycin-based antibiotic effective against Gram-negative bacterial infections and digestive disorders in poultry.",
    dosage: "1 g per 5–10 kg body weight",
    usage:
      "Recommended for Gram-negative bacterial infections and diarrhea management.",
    benefits: [
      "Controls Gram-negative bacteria",
      "Effective against diarrhea",
      "Supports gut health",
      "Improves productivity",
    ],
    packaging: "50 g, 100 g, 1 kg",
    composition: "Neomycin Sulphate 500 mg/g",
  },
  {
    id: 24,
    slug: "oxystan",
    name: "OXYSTAN",
    image: "/products/oxystan.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 93,
    isLatest: false,
    shortUsage: "Oxytetracycline HCl Water Soluble Powder",
    description:
      "OXYSTAN is a broad-spectrum oxytetracycline antibiotic formulated to control respiratory, enteric, and systemic bacterial infections in poultry.",
    dosage: "1 g per 2 kg body weight",
    usage:
      "Recommended for CRD, enteric infections, and systemic bacterial diseases.",
    benefits: [
      "Broad-spectrum antibacterial action",
      "Controls CRD",
      "Effective against enteric infections",
      "Supports flock health",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Oxytetracycline HCl 50 mg/g",
  },
  {
    id: 25,
    slug: "stanmulin-80",
    name: "STANMULLIN 80",
    image: "/products/stanmulin 80.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 95,
    isLatest: false,
    shortUsage: "Tiamulin 80% Feed Supplement",
    description:
      "STANMULIN 80 is a tiamulin-based feed supplement formulated for poultry feed applications.",
    dosage: "As directed by veterinarian",
    usage: "Feed supplementation for poultry.",
    benefits: [
      "Convenient feed administration",
      "Uniform mixing",
      "Supports flock performance",
      "Suitable for poultry feed programs",
    ],
    packaging: "1 kg",
    composition: "Tiamulin 80%",
  },
  {
    id: 26,
    slug: "stanbro-l",
    name: "STANBRO-L",
    image: "/products/stanbrol.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Antibiotics",
    popularity: 96,
    isLatest: false,
    shortUsage: "Levofloxacin & Bromhexine Oral Solution",
    description:
      "STANBRO-L combines levofloxacin with bromhexine to provide effective control of respiratory and bacterial infections while supporting respiratory tract clearance.",
    dosage: "1 ml/10 kg body weight or 1 ml/L water",
    usage:
      "Recommended for bronchitis, sinusitis, E. coli infections, Salmonellosis, and respiratory bacterial diseases.",
    benefits: [
      "Broad-spectrum antibacterial action",
      "Supports respiratory health",
      "Effective against E. coli and Salmonella",
      "Improves recovery from respiratory diseases",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Levofloxacin 100 mg/ml + Bromhexine HCl 7.5 mg/ml",
  },
  {
    id: 27,
    slug: "stanoflox",
    name: "STANOFLOX",
    image: "/products/stanoflox.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 94,
    isLatest: false,
    shortUsage: "Ofloxacin Water Soluble Powder",
    description:
      "STANOFLOX is a broad-spectrum ofloxacin antibiotic providing systemic distribution and effective control of bacterial infections in poultry.",
    dosage: "1 g/L water or 1 g/10 kg body weight",
    usage:
      "Recommended for Salmonellosis and other susceptible bacterial infections.",
    benefits: [
      "Broad-spectrum antibacterial activity",
      "Excellent systemic distribution",
      "Controls Salmonellosis",
      "Supports flock health",
    ],
    packaging: "500 g, 1 kg",
    composition: "Ofloxacin HCl 100 mg/g",
  },
  {
    id: 28,
    slug: "tilmostan",
    name: "TILMOSTAN-25",
    image: "/products/tilmostan.png",
    category: "Poultry",
    type: "Antibiotics",
    popularity: 97,
    isLatest: false,
    shortUsage: "Tilmicosin Phosphate Oral Solution",
    description:
      "TILMOSTAN-25 is a respiratory-focused antibiotic formulated for prevention and treatment of respiratory diseases and enzootic pneumonia in poultry.",
    dosage: "1 ml/16–20 kg body weight (prevention); 1 ml/12–16 kg body weight (treatment)",
    usage:
      "Recommended for respiratory diseases and enzootic pneumonia management.",
    benefits: [
      "Controls respiratory infections",
      "Supports lung health",
      "Effective in enzootic pneumonia",
      "Improves flock performance",
    ],
    packaging: "1 L",
    composition: "Tilmicosin Phosphate 250 mg/ml",
  },
  {
    id: 29,
    slug: "stanprim",
    name: "STANPRIM",
    image: "/products/stanprim.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Antibiotics",
    popularity: 93,
    isLatest: false,
    shortUsage: "Sulphamethoxazole & Trimethoprim Powder",
    description:
      "STANPRIM is a synergistic antibacterial formulation designed to control major bacterial infections affecting poultry health and productivity.",
    dosage: "1 g/L water for 5 days",
    usage:
      "Recommended for chick mortality syndrome, BWD, CRD, and infectious Coryza.",
    benefits: [
      "Controls chick mortality",
      "Effective against CRD",
      "Supports recovery from Coryza",
      "Improves flock health",
    ],
    packaging: "100 g, 500 g, 1 kg",
    composition: "Sulphamethoxazole 100 mg/g + Trimethoprim 20 mg/g",
  },
  {
    id: 30,
    slug: "ampromax",
    name: "AMPROMAX",
    image: "/products/ampromax.png",
    category: "Poultry",
    type: "Antiprotozoal",
    popularity: 94,
    isLatest: false,
    shortUsage: "Amprolium Soluble Powder",
    description:
      "AMPROMAX is an amprolium-based antiprotozoal formulation designed for the prevention and control of coccidiosis in poultry, helping maintain flock health and productivity.",
    dosage: "As directed by veterinarian",
    usage:
      "Recommended for the prevention and treatment of coccidiosis caused by Eimeria species in poultry.",
    benefits: [
      "Controls coccidiosis",
      "Supports intestinal health",
      "Improves feed utilization",
      "Enhances flock performance",
    ],
    packaging: "100 g, 1 kg",
    composition: "Amprolium 20% Soluble Powder",
  },
  {
    id: 31,
    slug: "ampromax-k",
    name: "AMPROMAX-K",
    image: "/products/ampromax k.png",
    category: "Poultry",
    type: "Antiprotozoal",
    popularity: 95,
    isLatest: false,
    shortUsage: "Amprolium & Vitamin K Soluble Powder",
    description:
      "AMPROMAX-K combines the anticoccidial efficacy of amprolium with Vitamin K support, helping birds recover quickly during coccidial challenges.",
    dosage: "As directed by veterinarian",
    usage:
      "Recommended for prevention and treatment of coccidiosis while supporting recovery from intestinal damage and blood loss.",
    benefits: [
      "Controls coccidiosis",
      "Supports recovery during outbreaks",
      "Provides Vitamin K supplementation",
      "Improves bird health and performance",
    ],
    packaging: "100 g, 1 kg",
    composition: "Amprolium 20% Soluble Powder + Vitamin K 0.2%",
  },
  {
    id: 32,
    slug: "coxy-cure",
    name: "COXY CURE",
    image: "/products/coxycure.png",
    category: "Poultry",
    type: "Antiprotozoal",
    popularity: 96,
    isLatest: false,
    shortUsage: "Amprolium & Sulfaquinoxaline Powder",
    description:
      "COXY CURE is a dual-action antiprotozoal formulation developed for effective prevention and control of coccidiosis and associated intestinal infections in poultry.",
    dosage: "As directed by veterinarian",
    usage:
      "Recommended for treatment and control of coccidiosis and protozoal intestinal infections in poultry.",
    benefits: [
      "Dual-action anticoccidial protection",
      "Controls protozoal infections",
      "Supports intestinal health",
      "Improves flock productivity",
    ],
    packaging: "100 g, 1 kg",
    composition: "Amprolium 20% + Sulfaquinoxaline 20%",
  },
  {
    id: 33,
    slug: "linconex",
    name: "LINCONEX",
    image: "/products/linconex.png",
    category: "Poultry",
    type: "Dewormers",
    popularity: 90,
    isLatest: false,
    shortUsage: "Nil",
    description: "Nil",
    dosage: "Nil",
    usage: "Nil",
    benefits: [
      "Nil",
    ],
    packaging: "1 kg",
    composition: "Nil",
  },
  {
    id: 34,
    slug: "nutrimax",
    name: "NUTRIMAX",
    image: "/products/nutrimax.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Vitamin Supplements",
    popularity: 94,
    isLatest: false,
    shortUsage: "Amino Acids, Vitamins & Minerals Supplement",
    description:
      "NUTRIMAX is a nutritional supplement containing a powerful combination of amino acids, vitamins, and minerals formulated to support poultry health and productivity.",
    dosage: "Nil",
    usage: "Nutritional supplementation",
    benefits: [
      "Amino acid supplementation",
      "Vitamin supplementation",
      "Mineral supplementation",
      "Supports poultry nutrition",
    ],
    packaging: "1 L, 2 L, 5 L",
    composition: "A powerful combination of Amino Acids, Vitamins & Minerals",
  },
  {
    id: 35,
    slug: "stancical-ds",
    name: "STANCICAL DS",
    image: "/products/stancical ds.png",
    category: "Poultry",
    type: "Vitamin Supplements",
    popularity: 93,
    isLatest: false,
    shortUsage: "Calcium, Phosphorous & Vitamin D Oral Liquid",
    description:
      "STANCICAL DS is an oral liquid supplement containing calcium, phosphorous, and Vitamin D.",
    dosage: "Nil",
    usage: "Mineral and vitamin supplementation",
    benefits: [
      "Calcium supplementation",
      "Phosphorous supplementation",
      "Vitamin D supplementation",
      "Supports nutritional requirements",
    ],
    packaging: "1 L, 5 L",
    composition: "Calcium, Phosphorous & Vitamin D Oral Liquid",
  },
  {
    id: 36,
    slug: "stanvita-ad3ec",
    name: "STANVITA AD3EC",
    image: "/products/stanvita.png",
    category: "Poultry",
    type: "Vitamin Supplements",
    popularity: 95,
    isLatest: false,
    shortUsage: "Vitamin AD3EC with Lysine & Methionine",
    description:
      "STANVITA AD3EC is a vitamin supplement enriched with essential vitamins, lysine, and methionine.",
    dosage: "Nil",
    usage: "Vitamin supplementation",
    benefits: [
      "Vitamin A supplementation",
      "Vitamin E supplementation",
      "Vitamin C supplementation",
      "Contains Lysine & Methionine",
    ],
    packaging: "500 ml, 1 L, 2 L",
    composition:
      "Vitamin A 250000 IU, Vitamin D3 25000 IU, Vitamin E 150 mg, Vitamin C 500 mg, Lysine 50 mg, Methionine 20 mg",
  },
  {
    id: 37,
    slug: "suraxa",
    name: "SURAXA",
    image: "/products/suraxa.png",
    category: ["Poultry", "Sheep & Goat"],
    type: "Vitamin Supplements",
    popularity: 96,
    isLatest: false,
    shortUsage: "Immunity Enhancer",
    description:
      "SURAXA is an immunity-enhancing nutritional supplement formulated for poultry.",
    dosage: "Nil",
    usage: "Immune support supplementation",
    benefits: [
      "Supports immunity",
      "Nutritional support",
      "Suitable for poultry",
      "Daily supplementation",
    ],
    packaging: "500 ml, 1 L, 5 L",
    composition: "Immunity Enhancer",
  },
  {
    id: 38,
    slug: "livomax-forte",
    name: "LIVOMAX FORTE",
    image: "/products/livomax forte.png",
    category: "Poultry",
    type: "Nutritional Supplements",
    popularity: 95,
    isLatest: false,
    shortUsage: "Liver Extract & Yeast Based Oral Liquid Feed Supplement",
    description:
      "LIVOMAX FORTE is a nutritional liver tonic enriched with liver extract, yeast extract, and B-complex vitamins to support metabolism, appetite, and overall poultry performance.",
    dosage: "As directed by veterinarian",
    usage:
      "Supports liver function, nutritional supplementation, and recovery during stress conditions.",
    benefits: [
      "Supports liver health",
      "Improves appetite",
      "Enhances nutrient utilization",
      "Promotes overall flock performance",
    ],
    packaging: "500 ml, 1 L, 2 L, 5 L",
    composition: "Liver Extract, Yeast Extract with B-Complex Vitamins Oral Liquid Feed Supplement",
  },
  {
    id: 39,
    slug: "eratox-ac-gold",
    name: "ERATOX AC GOLD",
    image: "/products/eratox ac gold.png",
    category: "Poultry",
    type: "Nutritional Supplements",
    popularity: 96,
    isLatest: false,
    shortUsage: "Toxin Binder Soluble Powder",
    description:
      "ERATOX AC GOLD is a toxin binder soluble powder formulated to help manage feed-borne toxins and support optimal poultry health and productivity.",
    dosage: "As directed by veterinarian",
    usage:
      "Used as a feed toxin binder to support gut health and reduce the impact of mycotoxin contamination.",
    benefits: [
      "Helps bind feed toxins",
      "Supports gut integrity",
      "Improves feed utilization",
      "Supports immune performance",
    ],
    packaging: "1 kg",
    composition: "Toxin Binder Soluble Powder for Poultry",
  },
  {
    id: 40,
    slug: "bactodox-n",
    name: "BACTODOX N",
    image: "/products/bactodox n.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 94,
    isLatest: false,
    shortUsage: "Neomycin & Doxycycline Feed Supplement",
    description:
      "BACTODOX N is a medicated feed supplement containing Neomycin and Doxycycline formulated to support poultry health and performance.",
    dosage: "As directed by veterinarian",
    usage: "Feed supplementation for poultry.",
    benefits: [
      "Supports flock health",
      "Easy feed administration",
      "Uniform feed mixing",
      "Supports productivity",
    ],
    packaging: "25 kg",
    composition: "Neomycin 2% + Doxycycline HCl 2% Feed Supplement",
  },
  {
    id: 41,
    slug: "t-f-s-200",
    name: "T F S - 200",
    image: "/products/tfs.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 93,
    isLatest: false,
    shortUsage: "Oxytetracycline Feed Supplement",
    description:
      "T F S - 200 is an oxytetracycline-based feed supplement designed for incorporation into poultry feed.",
    dosage: "As directed by veterinarian",
    usage: "Feed supplementation for poultry.",
    benefits: [
      "Easy feed incorporation",
      "Uniform feed distribution",
      "Supports flock management",
      "Suitable for poultry operations",
    ],
    packaging: "1 kg, 10 kg, 25 kg",
    composition: "Oxytetracycline Feed Supplement",
  },
  {
    id: 42,
    slug: "stanmulin-fs",
    name: "STANMULLIN FS",
    image: "/products/stanmulin fs.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 94,
    isLatest: false,
    shortUsage: "Tiamulin 10% Feed Supplement",
    description:
      "STANMULLIN FS is a tiamulin-based feed supplement formulated for poultry feed applications.",
    dosage: "As directed by veterinarian",
    usage: "Feed supplementation for poultry.",
    benefits: [
      "Easy feed incorporation",
      "Uniform feed distribution",
      "Supports flock management",
      "Suitable for poultry production systems",
    ],
    packaging: "1 kg",
    composition: "Tiamulin 10% Feed Supplement",
  },
  {
    id: 43,
    slug: "tiaoxy-plus",
    name: "TIAOXY PLUS",
    image: "/products/tiaoxy plus.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 96,
    isLatest: false,
    shortUsage: "Tiamulin & Oxytetracycline Feed Supplement",
    description:
      "TIAOXY PLUS is a combination feed supplement containing tiamulin and oxytetracycline formulated for poultry feed applications.",
    dosage: "As directed by veterinarian",
    usage: "Feed supplementation for poultry.",
    benefits: [
      "Combination formulation",
      "Convenient feed administration",
      "Uniform feed mixing",
      "Supports flock performance",
    ],
    packaging: "55 kg",
    composition: "Tiamulin 10% + Oxytetracycline 10% Feed Supplement",
  },
  {
    id: 44,
    slug: "lincomax",
    name: "LINCOMAX",
    image: "/products/lincomax fs.png",
    category: "Poultry",
    type: "Feed Supplements",
    popularity: 92,
    isLatest: false,
    shortUsage: "Nil",
    description: "Nil",
    dosage: "Nil",
    usage: "Nil",
    benefits: [
      "Nil",
    ],
    packaging: "1 kg",
    composition: "Nil",
  },
  {
    id: 45,
    slug: "arrow-suspension",
    name: "ARROW Suspension",
    image: "/products/Copy of arrow.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 95,
    isLatest: true,
    shortUsage: "Rafoxanide & Albendazole Oral Suspension",
    description:
      "ARROW Suspension is a broad-spectrum dewormer formulated to control flukes and gastrointestinal worms in sheep and goats while supporting animal productivity.",
    dosage: "15–20 ml per 30 kg body weight",
    usage:
      "Used for the control of liver flukes and gastrointestinal worm infestations.",
    benefits: [
      "Rapid reduction in fluke burden",
      "Controls gastrointestinal worms",
      "Improves appetite and body weight",
      "Supports milk yield and animal performance",
    ],
    packaging: "500 ml, 1 L",
    composition: "Rafoxanide 15 mg + Albendazole 25 mg",
  },
  {
    id: 46,
    slug: "clozomax-50",
    name: "CLOZOMAX-50",
    image: "/products/Copy of clozomax.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 94,
    isLatest: false,
    shortUsage: "Closantel Oral Solution",
    description:
      "CLOZOMAX-50 is a closantel oral solution formulated for effective control of liver flukes and blood-feeding parasites.",
    dosage:
      "1 ml/5 kg body weight (flukes); 1 ml/3 kg body weight (blood-sucking parasites)",
    usage:
      "Used for the treatment and control of fluke infestations and blood-sucking parasites.",
    benefits: [
      "Controls liver flukes",
      "Reduces parasite burden",
      "Improves appetite",
      "Supports weight gain and milk yield",
    ],
    packaging: "500 ml, 1 L",
    composition: "Closantel 50 mg/ml",
  },
  {
    id: 47,
    slug: "clozomax-i-gold",
    name: "CLOZOMAX-I GOLD",
    image: "/products/Copy of clozomax i gold.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 97,
    isLatest: true,
    shortUsage: "Closantel & Ivermectin Oral Solution",
    description:
      "CLOZOMAX-I GOLD combines closantel and ivermectin for broad-spectrum control of internal and external parasites.",
    dosage:
      "1 ml/10 kg body weight",
    usage:
      "Recommended for the management of flukes, worms, and parasitic infestations.",
    benefits: [
      "Rapid improvement in animal health",
      "Reduces worm burden",
      "Supports body weight gain",
      "Enhances milk production",
    ],
    packaging: "100 ml, 300 ml, 600 ml",
    composition: "Closantel 150 mg + Ivermectin 3 mg/ml",
  },
  {
    id: 48,
    slug: "clozomax-i",
    name: "CLOZOMAX-I",
    image: "/products/Copy of clozomax i.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 96,
    isLatest: false,
    shortUsage: "Closantel & Ivermectin Oral Solution",
    description:
      "CLOZOMAX-I is a combination dewormer formulated to provide broad-spectrum parasite control and improve productivity.",
    dosage:
      "3 ml/10 kg body weight",
    usage:
      "Used for the treatment and control of flukes and worm infestations.",
    benefits: [
      "Broad-spectrum deworming",
      "Improves appetite",
      "Supports body weight gain",
      "Enhances milk production",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Closantel 150 mg + Ivermectin 2 mg/ml",
  },
  {
    id: 49,
    slug: "niclomisole",
    name: "NICLOMISOLE",
    image: "/products/Copy of niclomisole.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 95,
    isLatest: false,
    shortUsage: "Niclosamide & Levamisole Oral Suspension",
    description:
      "NICLOMISOLE is a combination dewormer formulated for effective control of tapeworms and gastrointestinal parasites.",
    dosage:
      "1 ml/1.5 kg body weight",
    usage:
      "Recommended for the treatment of parasitic worm infestations in sheep and goats.",
    benefits: [
      "Faster recovery",
      "Improves feed conversion",
      "Supports livability",
      "Reduces parasite burden",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Niclosamide 500 mg + Levamisole 75 mg/5 ml",
  },
  {
    id: 50,
    slug: "niclomax-t",
    name: "NICLOMAX-T",
    image: "/products/Copy of niclomax t.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 96,
    isLatest: true,
    shortUsage: "Niclosamide & Triclabendazole Oral Suspension",
    description:
      "NICLOMAX-T is a dual-action dewormer designed to eliminate tapeworms and liver flukes while supporting liver health.",
    dosage:
      "6–8 ml per 30 kg body weight",
    usage:
      "Recommended for the treatment and control of tapeworm and liver fluke infestations.",
    benefits: [
      "Eliminates tapeworms",
      "Controls liver flukes",
      "Protects liver health",
      "Supports productivity",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Niclosamide 750 mg + Triclabendazole 250 mg/5 ml",
  },
  {
    id: 51,
    slug: "stanfen-plus",
    name: "STANFEN PLUS",
    image: "/products/Copy of stanfen plus.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 94,
    isLatest: false,
    shortUsage: "Niclosamide & Fenbendazole Oral Suspension",
    description:
      "STANFEN PLUS is a broad-spectrum dewormer formulated to control gastrointestinal parasites and support healthy growth.",
    dosage:
      "1 ml/1.5 kg body weight",
    usage:
      "Used for the treatment and control of worm infestations in sheep and goats.",
    benefits: [
      "Broad-spectrum deworming",
      "Faster action",
      "Improves weight gain",
      "Supports animal performance",
    ],
    packaging: "100 ml, 250 ml, 500 ml, 1 L",
    composition: "Niclosamide 100 mg + Fenbendazole 30 mg/ml",
  },
  {
    id: 52,
    slug: "stanfen-n",
    name: "STANFEN-N",
    image: "/products/Copy of stanfen n.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 93,
    isLatest: false,
    shortUsage: "Niclosamide & Fenbendazole Oral Suspension",
    description:
      "STANFEN-N is a broad-spectrum dewormer formulated for effective control of gastrointestinal parasites in sheep and goats.",
    dosage: "1 ml/1.5 kg body weight",
    usage: "Used for the treatment and control of worm infestations.",
    benefits: [
      "Broad-spectrum deworming",
      "Faster action",
      "Improves weight gain",
      "Supports animal health",
    ],
    packaging: "250 ml, 500 ml, 1 L",
    composition: "Niclosamide 75 mg + Fenbendazole 25 mg/ml",
  },
  {
    id: 53,
    slug: "oxysole-l",
    name: "OXYSOLE-L",
    image: "/products/Copy of oxysole l.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 94,
    isLatest: false,
    shortUsage: "Levamisole & Oxyclozanide Oral Suspension",
    description:
      "OXYSOLE-L is a broad-spectrum dewormer designed for effective control of internal parasites in sheep and goats.",
    dosage:
      "1 ml/2 kg body weight (sheep & goat); 2.5 ml/10 kg body weight (cattle)",
    usage: "Used for broad-spectrum parasite management.",
    benefits: [
      "Broad-spectrum activity",
      "Improves health status",
      "Supports reproduction",
      "Enhances productivity",
    ],
    packaging: "100 ml, 500 ml, 1 L",
    composition: "Levamisole 15 mg + Oxyclozanide 30 mg/ml",
  },
  {
    id: 54,
    slug: "oxysole-ds",
    name: "OXYSOLE-DS",
    image: "/products/Copy of oxysole ds.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 95,
    isLatest: false,
    shortUsage: "Oxyclozanide & Levamisole Oral Suspension",
    description:
      "OXYSOLE-DS is a concentrated broad-spectrum dewormer formulated to improve animal health and performance.",
    dosage: "1 ml/4 kg body weight",
    usage: "Used for the treatment and control of parasitic infestations.",
    benefits: [
      "Broad-spectrum parasite control",
      "Improves health",
      "Enhances performance",
      "Supports productivity",
    ],
    packaging: "250 ml, 500 ml, 1 L",
    composition: "Oxyclozanide 60 mg + Levamisole 30 mg/ml",
  },
  {
    id: 55,
    slug: "oxysole-ofs",
    name: "OXYSOLE-OFS",
    image: "/products/Copy of oxysole ofs.png",
    category: "Sheep & Goat",
    type: "Dewormers",
    popularity: 94,
    isLatest: false,
    shortUsage: "Oxyclozanide & Oxyfendazole Oral Suspension",
    description:
      "OXYSOLE-OFS is a broad-spectrum dewormer formulated to reduce parasite burden and improve productivity.",
    dosage: "1 ml/2–3 kg body weight",
    usage: "Used for the treatment and control of internal parasites.",
    benefits: [
      "Reduces parasite load",
      "Improves appetite",
      "Supports weight gain",
      "Enhances animal performance",
    ],
    packaging: "250 ml, 500 ml, 1 L",
    composition: "Oxyclozanide 30 mg + Oxyfendazole 15 mg/ml",
  },
];

export const featuredProducts = products
  .filter((product) => product.isLatest);

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
